/*
Created By:    Zachary Ordo
Created Date:  2021-02-15
Last Modified: 2022-02-16

This job builds a Date-Based PivotTable of select components at the Clearfork Plant.
*/

SET NOCOUNT ON
DECLARE @StartDate DateTime
DECLARE @EndDate DateTime
SET @StartDate = '08/31/2020 11:01'
SET @EndDate = DateAdd(day, DateDiff(day, 0, GetDate()), 1)
SET NOCOUNT OFF

CREATE TABLE #tempQry(
	[ActualDate] [datetime2](7) NOT NULL,
	[TagName] [nvarchar](256) NOT NULL,
	[Value] float NULL,
) ON [PRIMARY]
GO

INSERT INTO #tempQry ([ActualDate], [TagName], [Value])
	SELECT	[ActualDate],
		[TagName],
		[Value]
	FROM [GISViews].[dbo].[CFHISSVR02AnalogHisComps]
	WHERE [ActualDate] <> '09/14/2020'

INSERT INTO #tempQry ([ActualDate], [TagName], [Value])
	SELECT [ActualDate],
		[TagName],
		[Value]
	FROM [GISViews].[dbo].[CFHISSVR02AnalogHisMain]
	WHERE [ActualDate] <> '09/14/2020'

INSERT INTO [GISViews].[dbo].[CFHISSVR02Raw] ([ActualDate],[FQI-1045A_PrevDay],[FQI-1400A_PrevDay],[FQI-8000A_PrevDay],[FQI-8210A_PrevDay],[FQI-8220B_PrevDay],[FQI-9000A_PrevDay],[FQI-9110A_PrevDay],
			[GC1_INLET_BTU],[GC1_INLET_C1],[GC1_INLET_C2],[GC1_INLET_C2PLUS_GAL],[GC1_INLET_C3],[GC1_INLET_C3PLUS_GAL],[GC1_INLET_C6_PLUS],[GC1_INLET_CO2],[GC1_INLET_IC4],[GC1_INLET_IC5],[GC1_INLET_N2],
			[GC1_INLET_NC4],[GC1_INLET_NC5],[GC1_INLET_SGU],[GC1_RESIDUE_BTU],[GC1_RESIDUE_C1],[GC1_RESIDUE_C2],[GC1_RESIDUE_C2_RECOVER],[GC1_RESIDUE_C3],[GC1_RESIDUE_C3_RECOVER],[GC1_RESIDUE_C6_PLUS],
			[GC1_RESIDUE_CO2],[GC1_RESIDUE_IC4],[GC1_RESIDUE_IC5],[GC1_RESIDUE_N2],[GC1_RESIDUE_NC4],[GC1_RESIDUE_NC5],[GC1_RESIDUE_REL_DENS],[GC2_YGRADE_C1],[GC2_YGRADE_C2],[GC2_YGRADE_C2_LIQ_VOL],
			[GC2_YGRADE_C2C3_RATIO],[GC2_YGRADE_C3],[GC2_YGRADE_C6_PLUS],[GC2_YGRADE_IC4],[GC2_YGRADE_IC5],[GC2_YGRADE_NC4],[GC2_YGRADE_NC5])
(
	SELECT PIVOTED.* FROM

	(
	SELECT * FROM #tempQry
		) AS [P]

	PIVOT
		(
		MIN([P].[Value])
		FOR [TagName] IN ([FQI-1045A_PrevDay],[FQI-1400A_PrevDay],[FQI-8000A_PrevDay],[FQI-8210A_PrevDay],[FQI-8220B_PrevDay],[FQI-9000A_PrevDay],[FQI-9110A_PrevDay],[GC1_INLET_BTU],[GC1_INLET_C1],
			[GC1_INLET_C2],[GC1_INLET_C2PLUS_GAL],[GC1_INLET_C3],[GC1_INLET_C3PLUS_GAL],[GC1_INLET_C6_PLUS],[GC1_INLET_CO2],[GC1_INLET_IC4],[GC1_INLET_IC5],[GC1_INLET_N2],[GC1_INLET_NC4],
			[GC1_INLET_NC5],[GC1_INLET_SGU],[GC1_RESIDUE_BTU],[GC1_RESIDUE_C1],[GC1_RESIDUE_C2],[GC1_RESIDUE_C2_RECOVER],[GC1_RESIDUE_C3],[GC1_RESIDUE_C3_RECOVER],[GC1_RESIDUE_C6_PLUS],
			[GC1_RESIDUE_CO2],[GC1_RESIDUE_IC4],[GC1_RESIDUE_IC5],[GC1_RESIDUE_N2],[GC1_RESIDUE_NC4],[GC1_RESIDUE_NC5],[GC1_RESIDUE_REL_DENS],[GC2_YGRADE_C1],[GC2_YGRADE_C2],
			[GC2_YGRADE_C2_LIQ_VOL],[GC2_YGRADE_C2C3_RATIO],[GC2_YGRADE_C3],[GC2_YGRADE_C6_PLUS],[GC2_YGRADE_IC4],[GC2_YGRADE_IC5],[GC2_YGRADE_NC4],[GC2_YGRADE_NC5])
		) AS PIVOTED
)

DROP TABLE #tempQry